### ISSUE TITLE
Conda setup issue

### ISSUE THREAD

**Issue by matteorr** [kmeng01/rome#36]
There seems to be a dependency issue between the `checklist` and the `notebook` packages. 
I kept getting the following error when trying to install using `./scripts/setup_conda.sh`:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/tmp/pip-install-agcyk1c_/checklist_cdbf3a4517814d0a8ddc1381fe4d54ce/setup.py", line 56, in <module>
        setup(name='checklist',
      File "/miniconda/envs/rome/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
      File "/miniconda/envs/rome/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/miniconda/envs/rome/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/miniconda/envs/rome/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/miniconda/envs/rome/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/miniconda/envs/rome/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/mnt/tmp/pip-install-agcyk1c_/checklist_cdbf3a4517814d0a8ddc1381fe4d54ce/setup.py", line 53, in run
        enable_visual_interface()
      File "/mnt/tmp/pip-install-agcyk1c_/checklist_cdbf3a4517814d0a8ddc1381fe4d54ce/setup.py", line 14, in enable_visual_interface
        notebook.nbextensions.install_nbextension_python(
    AttributeError: module 'notebook' has no attribute 'nbextensions'
    ----------------------------------------
Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement checklist==0.0.11 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11)
ERROR: No matching distribution found for checklist==0.0.11
```

I had to fix by reverting version of notebook to `5.6.0` in the `rome.yml` file.

**Comment by ZHANGJINKUI** [comment]
it is still error after  notebook to 5.6.0

    AttributeError: module 'notebook' has no attribute 'nbextensions'
    ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/38/b3/8511f50025b9fc66f5feacf9eb2db044c321f4026b6937cb3820f29e9c1d/checklist-0.0.11.tar.gz#sha256=427cf87dbf47ce9f9ab059a9bbf393d9ebf967e266f8fca377420bd6995a95ac (from https://pypi.tuna.tsinghua.edu.cn/simple/checklist/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement checklist==0.0.11 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11)
ERROR: No matching distribution found for checklist==0.0.11

failed

CondaEnvException: Pip failed

**Comment by Kevin3777** [comment]
> it is still error after notebook to 5.6.0笔记本到 5.6.0 后还是报错
> 
> ```
> AttributeError: module 'notebook' has no attribute 'nbextensions'
> ----------------------------------------
> ```
> 
> WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/38/b3/8511f50025b9fc66f5feacf9eb2db044c321f4026b6937cb3820f29e9c1d/checklist-0.0.11.tar.gz#sha256=427cf87dbf47ce9f9ab059a9bbf393d9ebf967e266f8fca377420bd6995a95ac (from https://pypi.tuna.tsinghua.edu.cn/simple/checklist/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.警告： 丢弃 https://pypi.tuna.tsinghua.edu.cn/packages/38/b3/8511f50025b9fc66f5feacf9eb2db044c321f4026b6937cb3820f29e9c1d/checklist-0.0.11.tar.gz#sha256=427cf87dbf47ce9f9ab059a9bbf393d9ebf967e266f8fca377420bd6995a95ac（来自 https://pypi.tuna.tsinghua.edu.cn/simple/checklist/）。命令出错，退出状态为 1：python setup.py egg_info 检查日志以获取完整的命令输出。 ERROR: Could not find a version that satisfies the requirement checklist==0.0.11 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11)错误：找不到满足需求清单==0.0.11 的版本（来自版本：0.0.1、0.0.2、0.0.3、0.0.4、0.0.6、0.0.7、0.0.8、0.0.9、0.0.10、0.0.11） ERROR: No matching distribution found for checklist==0.0.11错误：未找到与 checklist==0.0.11 匹配的分布
> 
> failed  失败
> 
> CondaEnvException: Pip failedCondaEnvException：Pip 失败

Did you find the way to fix it? Thanks!
